version: '3'
services:
  web:
    image: wishlist:0.1
    env_file:
      - database.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6.12
    env_file:
      - database.env