version: '3'
services:
  web:
    image: wishlist:0.1
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.6.12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wishlist